export type Theme = 'light' | 'dark'
export type ViewMode = 'grid' | 'list'
export type ViewType = 'all' | 'archive'

// Item types
export type ContentType = 'article' | 'video' | 'post' | 'podcast' | 'book' | 'note'
export type ItemStatus = 'inbox' | 'queued' | 'reading' | 'done' | 'archived'
export type MetadataStatus = 'pending' | 'processing' | 'completed' | 'failed'

export interface Item {
  id: string
  url: string | null
  title: string
  type: ContentType
  createdAt: string
  status: ItemStatus
  metadataStatus: MetadataStatus

  // Enriched metadata (populated after extraction)
  description: string | null
  imageUrl: string | null
  imageWidth: number | null
  imageHeight: number | null
  siteName: string | null
  author: string | null
  readingTime: number | null

  // Enrichment tracking
  enrichmentSource: string | null
  rawInput: string
  pageCount: number | null

  // Tags
  tags?: { tag: { name: string; slug: string; color: string; isAutoGenerated: boolean } }[]
}
