import { describe, expect, it } from 'vitest'
import { getTopicTags } from '../tag-utils'
import type { Item } from '../types'

const baseItem: Item = {
  id: '1',
  url: 'https://every.to/some-article',
  title: 'Compound Engineering',
  type: 'article',
  createdAt: '2025-01-01',
  status: 'inbox',
  metadataStatus: 'completed',
  description: null,
  imageUrl: null,
  imageWidth: null,
  imageHeight: null,
  siteName: 'Every',
  author: null,
  readingTime: null,
  enrichmentSource: null,
  rawInput: 'https://every.to/some-article',
  pageCount: null,
}

function tag(name: string, slug: string, color = '#6B7280') {
  return { tag: { name, slug, color, isAutoGenerated: true } }
}

describe('getTopicTags', () => {
  it('returns empty for items without tags', () => {
    expect(getTopicTags(baseItem)).toEqual([])
  })

  it('filters out type tags', () => {
    const item = {
      ...baseItem,
      tags: [tag('Article', 'article'), tag('AI', 'ai', '#3B82F6')],
    }
    const result = getTopicTags(item)
    expect(result).toHaveLength(1)
    expect(result[0].slug).toBe('ai')
  })

  it('filters out domain tags', () => {
    const item = {
      ...baseItem,
      tags: [tag('YouTube', 'youtube'), tag('React', 'react')],
    }
    const result = getTopicTags(item)
    expect(result).toHaveLength(1)
    expect(result[0].slug).toBe('react')
  })

  it('filters out tags matching item siteName', () => {
    const item = {
      ...baseItem,
      siteName: 'Every',
      tags: [
        tag('Every', 'every'),
        tag('software-engineering', 'software-engineering'),
        tag('ai-assisted-development', 'ai-assisted-development'),
      ],
    }
    const result = getTopicTags(item)
    expect(result).toHaveLength(2)
    expect(result.map((t) => t.slug)).toEqual(['software-engineering', 'ai-assisted-development'])
  })

  it('filters siteName case-insensitively', () => {
    const item = {
      ...baseItem,
      siteName: 'Mistral AI',
      tags: [tag('Mistral AI', 'mistral-ai'), tag('llm', 'llm')],
    }
    const result = getTopicTags(item)
    expect(result).toHaveLength(1)
    expect(result[0].slug).toBe('llm')
  })

  it('filters all overlap categories together', () => {
    const item = {
      ...baseItem,
      siteName: 'TrustMRR',
      tags: [tag('Article', 'article'), tag('TrustMRR', 'trustmrr'), tag('saas', 'saas')],
    }
    const result = getTopicTags(item)
    expect(result).toHaveLength(1)
    expect(result[0].slug).toBe('saas')
  })
})
