import type { TransactionClient } from '@/lib/db'
import { logger } from '@/lib/logger'
import type { AutoTag } from './auto-tagger'

export async function applyTags(
  tx: TransactionClient,
  itemId: string,
  tags: readonly AutoTag[],
): Promise<void> {
  for (const tagData of tags) {
    const tag = await tx.tag.upsert({
      where: { slug: tagData.slug },
      create: {
        name: tagData.name,
        slug: tagData.slug,
        color: tagData.color,
        isAutoGenerated: true,
      },
      update: {},
    })

    await tx.itemTag
      .create({
        data: {
          itemId,
          tagId: tag.id,
          isAutoGenerated: true,
        },
      })
      .catch((err) => {
        logger.debug('ItemTag create skipped (likely duplicate)', {
          itemId,
          tagId: tag.id,
          err,
        })
      })
  }
}

export async function fetchTagNames(tx: TransactionClient): Promise<string[]> {
  const tags = await tx.tag.findMany({
    select: { name: true },
    take: 200,
  })
  return tags.map((t) => t.name)
}
