import type { TransactionClient } from '@/lib/db'
import { describe, expect, it, vi } from 'vitest'
import { applyTags, fetchTagNames } from '../apply-tags'
import type { AutoTag } from '../auto-tagger'

function createMockTx() {
  return {
    tag: {
      upsert: vi.fn().mockResolvedValue({ id: 'tag-1' }),
      findMany: vi.fn().mockResolvedValue([]),
    },
    itemTag: {
      create: vi.fn().mockResolvedValue({}),
      findMany: vi.fn().mockResolvedValue([]),
    },
  } as unknown as TransactionClient & {
    tag: { upsert: ReturnType<typeof vi.fn>; findMany: ReturnType<typeof vi.fn> }
    itemTag: { create: ReturnType<typeof vi.fn>; findMany: ReturnType<typeof vi.fn> }
  }
}

describe('applyTags', () => {
  it('upserts Tag + creates ItemTag per tag', async () => {
    const tx = createMockTx()
    const tags: AutoTag[] = [
      { name: 'React', slug: 'react', color: '#61DAFB' },
      { name: 'TypeScript', slug: 'typescript', color: '#3178C6' },
    ]

    await applyTags(tx, 'item-1', tags)

    expect(tx.tag.upsert).toHaveBeenCalledTimes(2)
    expect(tx.tag.upsert).toHaveBeenCalledWith({
      where: { slug: 'react' },
      create: {
        name: 'React',
        slug: 'react',
        color: '#61DAFB',
        isAutoGenerated: true,
      },
      update: {},
    })
    expect(tx.itemTag.create).toHaveBeenCalledTimes(2)
  })

  it('catches duplicate ItemTag errors', async () => {
    const tx = createMockTx()
    tx.itemTag.create.mockRejectedValue(new Error('Unique constraint failed'))

    const tags: AutoTag[] = [{ name: 'React', slug: 'react', color: '#61DAFB' }]

    // Should not throw
    await expect(applyTags(tx, 'item-1', tags)).resolves.toBeUndefined()
  })
})

describe('fetchTagNames', () => {
  it('returns string[], caps at 200', async () => {
    const tx = createMockTx()
    tx.tag.findMany.mockResolvedValue([{ name: 'react' }, { name: 'typescript' }])

    const names = await fetchTagNames(tx)

    expect(names).toEqual(['react', 'typescript'])
    expect(tx.tag.findMany).toHaveBeenCalledWith({
      select: { name: true },
      take: 200,
    })
  })
})
